### ISSUE TITLE
report a bug and my fix code

### ISSUE THREAD

**Issue by RainMolisa** [discopop-project/discopop#667]
hello Discopop！
I find Discopop will crash in following target code.
``` c++
#include <vector>
#include <algorithm>
#include <iostream>
using namespace std;
int a = 0;
int C(int a) {
    int sum = 0;
    vector<int> c {1,2,3,4,5,6,7,8};
    for_each(c.begin(), c.end(), [&](int item) {
          sum += item * a;
    });
    return sum;
}
int B() {
    int b = 1;
    a++;
    return C(a);
}
void A() {
   a = 100;
}
int main()
{
    A();
    int b = B();
    int c = C(2);
    cout<<"b="<<b<<",c="<<c<<endl;
    return 0;
}
```
And , I find the bug is in Discopop/DiscoPoP.cpp
``` C++
        // Remove values from locals if dereferenced
        if (isa<StoreInst>(I)) {
          V = I.getOperand(0);
          for (Value *w : staticallyPredictableValues) {
            if (w == V) {
              staticallyPredictableValues.erase(V);
            }
          }
```
To fix the bug, I change the code into following:
```
          while(staticallyPredictableValues.end() != staticallyPredictableValues.find(V)){
            staticallyPredictableValues.erase(V);
          }
```
It's work!

Best Wish!

**Comment by lukasrothenberger** [comment]
Hi @RainMolisa 
this bug is one of multiples that should be fixed by the upcoming Release 4.0 (#615).
Until the release, i would suggest to try your code again using the DiscoPoP version in branch "release/4.0.0", as this is the most reliable state as of now. 

I will try to prepare the release as soon as possible.

Regarding your code snippet: I have tested it and it did work with branch "release/4.0.0". If you encounter any issue, please feel free to let me know, I'll be happy to help!

Best regards
Lukas

**Comment by lukasrothenberger** [comment]
Hi @RainMolisa 
could you please re-try with the latest release 4.0.0?

**Comment by RainMolisa** [comment]
> Hi @RainMolisa could you please re-try with the latest release 4.0.0?

I will try, later.
